function [fitresult, gof, speedBest, maxRange] = createFit2(speed, range)
%CREATEFIT(SPEED,RANGE)
%  Create a fit.
%
%  Data for 'CustomFit' fit:
%      X Input: speed
%      Y Output: range
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Feb-2025 11:57:40


%% Fit: 'CustomFit'.
[xData, yData] = prepareCurveData( speed, range );

% Set up fittype and options.
ft = fittype( 'evModel2(x,battEfficiency,auxPower)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.730330862855453 0.488608973803579];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

d = differentiate(fitresult,speed);
[~, idx] = min(abs(d));
speedBest = speed(idx);
maxRange = feval(fitresult, speedBest);